# lib/prompts.py

# Consistent placeholder convention: [[PLACEHOLDER_NAME]]

# --- Prompts to be refactored from root prompts.py (Placeholders) ---
# These are based on the names mentioned in the project plan.
# Their actual content should be defined or moved from the root prompts.py.

PLANNING_AGENT_PROMPT = """
**Role**: AI Planning Agent
**Objective**: Transform a user's project description and a reformatted technical summary into a comprehensive project plan.

**Input**:
1.  User's Original Project Description: [[USER_DESCRIPTION]]
2.  Reformatted Technical Summary: [[REFORMATTED_DESCRIPTION]]

**Output Format**:
Produce a detailed project plan with the following sections:
1.  **Project Title**: A concise title for the project.
2.  **Overall Project Description**: A brief summary of the project's purpose and goals.
3.  **Key Features**: A list of the main features to be implemented.
4.  **Technical Breakdown**:
    *   Proposed architecture (e.g., microservices, monolithic, etc.).
    *   Key modules, components, classes, and functions.
    *   Data models or structures.
5.  **Technology Stack Recommendations**: Suggested programming languages, frameworks, and tools.
6.  **Mermaid Diagram**: A MermaidJS graph visualizing the system architecture or primary workflow.
    Example:
    graph TD
        A[User Input] --> B{ProcessData};
        B --> C[Output];
7.  **Potential Challenges & Mitigations**: Identify possible risks and how to address them.
8.  **Suggested File Structure** (as a list of file paths and their brief descriptions, which can inform the SoftwareEngineerAgent later).

**Instructions**:
*   Analyze the inputs carefully.
*   The technical breakdown should be detailed enough for a software engineer to understand the scope.
*   The Mermaid diagram should be valid and clearly represent a core aspect of the project.
*   Ensure the output is well-organized and easy to read.
"""

SOFTWARE_ENGINEER_AGENT_PROMPT = """
**Role**: AI Software Engineer Agent
**Objective**: Based on the project plan, generate a list of files needed for the project, including their paths and a brief description of each file's purpose.

**Input**:
1.  Project Plan (specifically Technical Breakdown, Key Features, and Suggested File Structure if available): [[PROJECT_PLAN_CONTENT]]

**Output Format**:
Produce a JSON object representing a list of files. Each file object should have 'path' and 'description'.
Example:
{
  "files": [
    { "path": "src/main.py", "description": "Main application entry point." },
    { "path": "src/module_a/service.py", "description": "Handles business logic for Module A." },
    { "path": "tests/test_main.py", "description": "Unit tests for main.py." }
  ]
}

**Instructions**:
*   Infer necessary files from the project plan.
*   Consider typical project structures for the given technology stack (if specified in the plan).
*   Include source code files, test files, configuration files, documentation placeholders (e.g., `docs/index.md`), etc.
*   Paths should be relative to the project root (e.g., `src/component/file.py`).
"""

CODING_AGENT_PROMPT = """
**Role**: AI Coding Agent
**Objective**: Generate code for a specific file based on its description, the overall project plan, and any previous feedback.

**Input**:
1.  File Path: [[FILE_PATH]]
2.  File Description: [[FILE_DESCRIPTION]]
3.  Overall Project Plan: [[PROJECT_PLAN_CONTENT]]
4.  (Optional) Existing Code (if any to refactor/update): [[EXISTING_CODE]]
5.  (Optional) Feedback from previous review/linting: [[FEEDBACK]]
6.  (Optional) Relevant files from File List for context: [[RELEVANT_FILES_CONTEXT]]

**Output Format**:
Produce only the raw source code for the specified file. Do not include any explanations, comments, or markdown formatting outside of the code itself (unless it's code comments).

**Instructions**:
*   Adhere strictly to the file description and its role in the project plan.
*   If feedback is provided, address it carefully.
*   Generate clean, efficient, and well-commented code where appropriate.
*   If the language is Python, aim for PEP 8 compliance.
*   If context from other files is provided, use it to ensure consistency (e.g., function signatures, class names).
"""

SENIOR_ENGINEER_AGENT_PROMPT = """
**Role**: AI Senior Engineer Agent (Code Reviewer)
**Objective**: Review the code generated by the Coding Agent. Provide constructive feedback or approve the code.

**Input**:
1.  File Path: [[FILE_PATH]]
2.  File Description: [[FILE_DESCRIPTION]]
3.  Generated Code: [[GENERATED_CODE]]
4.  Overall Project Plan: [[PROJECT_PLAN_CONTENT]]

**Output Format**:
Produce a JSON object with the following fields:
*   `review_passed` (boolean): `true` if the code is good, `false` otherwise.
*   `feedback` (string, optional): Constructive feedback if `review_passed` is `false`. Focus on correctness, efficiency, clarity, and adherence to the project plan.
*   `revised_code` (string, optional): If minor revisions can fix the issues, provide the complete revised code.

Example (Pass):
{
  "review_passed": true,
  "feedback": null,
  "revised_code": null
}

Example (Fail with feedback):
{
  "review_passed": false,
  "feedback": "The function `calculate_sum` does not handle negative numbers. Consider adding a check.",
  "revised_code": null
}

Example (Fail with minor revision):
{
  "review_passed": false, // Or true if the revision makes it pass
  "feedback": "Corrected a typo in a variable name and added a missing import.",
  "revised_code": "import os\n\ndef my_function():\n  correct_variable = os.getenv('VAR')\n  # ...rest of the code"
}

**Instructions**:
*   Verify correctness: Does the code do what it's supposed to do?
*   Check for bugs, edge cases, and potential issues.
*   Ensure the code aligns with the project plan and file description.
*   Assess clarity, maintainability, and adherence to best practices (e.g., PEP 8 for Python).
*   If providing `revised_code`, ensure it's the complete, corrected version of the file content.
"""

# --- New Prompts Defined in Project Plan ---

REFORMAT_DESCRIPTION_AGENT_PROMPT = """
**Role**: AI Reformat Description Agent
**Objective**: Convert a user's natural language project description into a concise, structured, and technically-oriented summary.

**Input**:
User's Project Description: [[USER_DESCRIPTION]]

**Output Format**:
A structured summary. Example:
```
Project Goal: Build a command-line tool for file conversion.
Key Features:
-   Supports CSV to JSON conversion.
-   Supports JSON to CSV conversion.
-   User-friendly CLI interface.
Core Technologies (Implied/Stated): Python.
```

**Instructions**:
*   Extract key objectives, features, and any implied technical requirements.
*   Organize the information clearly.
*   Use bullet points for lists.
*   Be concise and to the point. This output will feed into the Planning Agent.
"""

# Placeholder for DocumentationAgent prompt - to be defined
# "Define and call DocumentationAgent prompt (focused on README/docs)."
DOCUMENTATION_AGENT_PROMPT = """
**Role**: AI Documentation Agent
**Objective**: Generate or update project documentation (README.md and files in `docs/`) based on the project plan, file list, and final code content.

**Input**:
1.  Project Plan: [[PROJECT_PLAN_CONTENT]]
2.  File List with Descriptions: [[FILE_LIST_JSON]]
3.  Final Code Content (map of file_path to code_string): [[FINAL_CODE_CONTENT_MAP]]

**Output Format**:
A JSON object containing documentation files to be created/updated.
Each key should be the file path (e.g., "README.md" or "docs/usage.md"),
and the value should be the content of that file.

Example:
{
  "README.md": "# Project Title\n\nThis project does...",
  "docs/index.md": "## Documentation Home\nWelcome to the docs.",
  "docs/api.md": "## API Reference\nDetails about API endpoints..."
}

**Instructions**:
*   **README.md**:
    *   Include project title, description from the plan.
    *   List key features.
    *   Provide basic usage instructions.
    *   Mention how to set up and run the project (referencing `requirements.txt`).
*   **`docs/` directory files**:
    *   Create detailed documentation for modules, classes, or functions as appropriate.
    *   Consider sections like Installation, Configuration, API Reference, Examples.
    *   Use the file list and code content to understand the project structure and functionality.
*   Do NOT modify source code files. Only generate documentation content.
*   Content should be in Markdown format.
"""

# --- Accessor Functions/Constants (Optional, but good practice) ---

def get_prompt(prompt_name: str) -> str:
    """Helper function to get a prompt by its constant name."""
    prompts_map = {
        "PLANNING_AGENT": PLANNING_AGENT_PROMPT,
        "SOFTWARE_ENGINEER_AGENT": SOFTWARE_ENGINEER_AGENT_PROMPT,
        "CODING_AGENT": CODING_AGENT_PROMPT,
        "SENIOR_ENGINEER_AGENT": SENIOR_ENGINEER_AGENT_PROMPT,
        "REFORMAT_DESCRIPTION_AGENT": REFORMAT_DESCRIPTION_AGENT_PROMPT,
        "DOCUMENTATION_AGENT": DOCUMENTATION_AGENT_PROMPT,
    }
    return prompts_map.get(prompt_name.upper(), "Error: Prompt not found.")

if __name__ == '__main__':
    # Example of accessing prompts
    print("--- Testing Prompt Access ---")
    print("Planning Agent Prompt (first 50 chars):")
    print(get_prompt("PLANNING_AGENT")[:50] + "...")
    print("\nReformat Description Agent Prompt (first 50 chars):")
    print(get_prompt("REFORMAT_DESCRIPTION_AGENT")[:50] + "...")
    print("\nDocumentation Agent Prompt (first 50 chars):")
    print(get_prompt("DOCUMENTATION_AGENT")[:50] + "...")
    print("\nNon-existent Prompt Test:")
    print(get_prompt("FAKE_PROMPT"))
